### ISSUE TITLE
USER STORY: Create comment on posts

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-react-frontend-the-winding-path#17]
As a user I can comment on walk and gallery posts so that I can communicate my thoughts and opinions with other users. 

## Acceptance Criteria

 - [x] A comment form will be available on walk and gallery post pages.
 - [x] Once submitted, comment will show in comments list within post page.
  
## Tasks
  
 - [x] Add comment form to gallery and walk post pages
